Models/ErrorViewModel.cs
using System;

namespace MvcMovie.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MovieKategoryViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace MvcMovie.Models
{
    public class MovieKategoryViewModel
    {
        public List<Spicyo> Spicyo { get; set; }
        public SelectList Kategorys { get; set; }
        public string MovieKategory { get; set; }
        public string SearchString { get; set; }
    }
}

Models/SeedData.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using MvcMovie.Data;
using System;
using System.Linq;

namespace MvcMovie.Models
{
    public static class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new MvcSpicyoContext(
                serviceProvider.GetRequiredService<
                    DbContextOptions<MvcSpicyoContext>>()))
            {
                // Look for any movies.
                if (context.Spicyo.Any())
                {
                    return;   // DB has been seeded
                }

                context.SaveChanges();
            }
        }
    }
}

Models/Spicyo.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcMovie.Models
{
    public class Spicyo
    {
        public int Id { get; set; }

        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string FoodName { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Order Date")]
        [DataType(DataType.Date)]
        public DateTime OrderDate { get; set; }

        [Range(1, 100000)]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 0)")]
        public decimal Price { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z]*$")]
        [Required]
        [StringLength(30)]
        public string Kategory { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z0-9""'\s-]*$")]
        [StringLength(1000)]
        [Required]
        public string Riview { get; set; }
    }
}

Controllers/SpicyoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcMovie.Data;
using MvcMovie.Models;

namespace MvcMovie.Controllers
{
    public class SpicyoController : Controller
    {
        private readonly MvcSpicyoContext _context;

        public SpicyoController(MvcSpicyoContext context)
        {
            _context = context;
        }

        // GET: Movies
        // GET: Movies
        public async Task<IActionResult> Index(string movieKategory, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> KategoryQuery = from m in _context.Spicyo
                                               orderby m.Kategory
                                               select m.Kategory;

            var movies = from m in _context.Spicyo
                         select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.FoodName.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(movieKategory))
            {
                movies = movies.Where(x => x.Kategory == movieKategory);
            }

            var movieKategoryVM = new MovieKategoryViewModel
            {
                Kategorys = new SelectList(await KategoryQuery.Distinct().ToListAsync()),
                Spicyo = await movies.ToListAsync()
            };

            return View(movieKategoryVM);
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Spicyo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // POST: Movies/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("ID,FoodName,OrderDate,Kategory,Price, Riview")] Spicyo movie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(movie);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Spicyo.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FoodName,OrderDate,Kategory,Price, Riview")] Spicyo movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Spicyo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Spicyo.FindAsync(id);
            _context.Spicyo.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
            return _context.Spicyo.Any(e => e.Id == id);
        }
    }
}

Controllers/TemplatesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcMovie.Models;

namespace MvcMovie.Controllers
{
    public class TemplatesController : Controller
    {
        private readonly ILogger<TemplatesController> _logger;

        public TemplatesController(ILogger<TemplatesController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Blog()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Recipe()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Spicyo</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/responsive.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Templates" asp-action="Index"><img
                        src="../images/logo.png" alt="logo" /></span></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between"
                    style="margin-left: 580px;">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Templates"
                                asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Templates"
                                asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Templates"
                                asp-action="Blog">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Templates"
                                asp-action="Contact">Contact</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Templates"
                            asp-action="Recipe">Recipe</a>
                            </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Spicyo" asp-action="Index">Your
                                Order</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Spicyo/Create.cshtml
@model MvcMovie.Models.Spicyo

@{
    ViewData["Title"] = "Create";
}

<br><br><br><br><br><br><br>
<h1><b>Order Now</b></h1>
<div class="row" style="background: orange;">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FoodName" class="control-label"></label>
                <input asp-for="FoodName" class="form-control" />
                <span asp-validation-for="FoodName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kategory" class="control-label"></label>
                <input asp-for="Kategory" class="form-control" />
                <span asp-validation-for="Kategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Riview" class="control-label"></label>
                <input asp-for="Riview" class="form-control" />
                <span asp-validation-for="Riview" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" style="color: red;"><u>Back to List</u></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Spicyo/Delete.cshtml
@model MvcMovie.Models.Spicyo

@{
    ViewData["Title"] = "Delete";
}

<br><br><br><br><br><br><br>
<h1>Delete</h1>
<h3>Are you sure you want to delete this?</h3>
<div style="background: orange;">
    <dl class=" row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FoodName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FoodName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Kategory)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Kategory)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Riview)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Riview)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" style="color: red;"><u>Back to List</u></a>
    </form>
</div>

Views/Spicyo/Details.cshtml
@model MvcMovie.Models.Spicyo

@{
    ViewData["Title"] = "Details";
}

<br><br><br><br><br><br><br>
<h1>Details</h1>
<div style="background: orange;">
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FoodName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FoodName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Kategory)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Kategory)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Riview)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Riview)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id"><u>Edit</u></a> |
    <a asp-action="Index" style="color: red;"><u>Back to List</u></a>
</div>

Views/Spicyo/Edit.cshtml
@model MvcMovie.Models.Spicyo

@{
    ViewData["Title"] = "Edit";
}

<br><br><br><br><br><br><br>
<h1>Edit</h1>
<div class="row" style="background: orange;">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FoodName" class="control-label"></label>
                <input asp-for="FoodName" class="form-control" />
                <span asp-validation-for="FoodName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kategory" class="control-label"></label>
                <input asp-for="Kategory" class="form-control" />
                <span asp-validation-for="Kategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Riview" class="control-label"></label>
                <input asp-for="Riview" class="form-control" />
                <span asp-validation-for="Riview" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" style="color: red;"><u>Back to List</u></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Spicyo/Index.cshtml
@model MvcMovie.Models.MovieKategoryViewModel

@{
    ViewData["Title"] = "Index";
}

<br><br><br><br><br><br><br>
<h1><b>Your Orders</b></h1>

<p>
    <a asp-action="Create" style="color: blue;"><u>Order Now</u></a>
</p>
<form asp-controller="Spicyo" asp-action="Index" method="get">
    <p>
        <select asp-for="MovieKategory" asp-items="Model.Kategorys">
            <option value="">All</option>
        </select>

        Title: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Filter" class="btn btn-primary" style="margin-bottom: 10px;" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Spicyo[0].FoodName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Spicyo[0].OrderDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Spicyo[0].Kategory)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Spicyo[0].Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Spicyo[0].Riview)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Spicyo)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FoodName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Kategory)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Riview)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" style="color: green;">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id" style="color: blue;">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" style="color: red;">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<fooetr>
    <div class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class=" col-md-12">
                    <h2>Request A<strong class="white"> Call Back</strong></h2>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">

                    <form class="main_form">
                        <div class="row">

                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                                <input class="form-control" placeholder="Name" type="text" name="Name">
                            </div>
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                                <input class="form-control" placeholder="Email" type="text" name="Email">
                            </div>
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                                <input class="form-control" placeholder="Phone" type="text" name="Phone">
                            </div>
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                                <textarea class="textarea" placeholder="Message" type="text" name="Message"></textarea>
                            </div>
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                                <button class="send">Send</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                    <div class="img-box">
                        <figure><img src="../images/img.jpg" alt="img" /></figure>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="footer_logo">
                        <a href="index.html"><img src="../images/logo1.jpg" alt="logo" /></a>
                    </div>
                </div>
                <div class="col-md-12">
                    <ul class="lik">
                        <li> <a href="~/Templates/Index">Home</a></li>
                        <li> <a href="~/Templates/About">About</a></li>
                        @* <li> <a href="~/Templates/Recipe">Recipe</a></li> *@
                        <li> <a href="~/Templates/Blog">Blog</a></li>
                        <li> <a href="~/Templates/Contact">Contact us</a></li>
                        <li class="active"> <a href="~/Movies/Index">Your Order</a></li>
                    </ul>
                </div>
                <div class="col-md-12">
                    <div class="new">
                        <h3>Newsletter</h3>
                        <form class="newtetter">
                            <input class="tetter" placeholder="Your email" type="text" name="Your email">
                            <button class="submit">Subscribe</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright">
            <div class="container">
                <p>© 2021 All Rights Reserved. Spicyo</a></p>
            </div>
        </div>
    </div>
</fooetr>